### ISSUE TITLE
Apply German review

### ISSUE THREAD

**Issue by kalbermattenm** [geomapfish/geomapfish_website#10]
Thanks @svavoi

![image](https://cloud.githubusercontent.com/assets/1681332/22333639/6c248cda-e3d7-11e6-9650-62cfebc52522.png)

**Comment by rbovard** [comment]
Can you paste raw data, I can apply it if you want.

**Comment by kalbermattenm** [comment]
I forwarded you the email... I am happy if you can do it, else I will do it during the week-end...
