### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by rbovard** [geomapfish/geomapfish_website#15]
Some details to look at:
* [x] Pages sorting in the menu #17
* [x] Location of translation links
* [x] Use new logo #20

**Comment by kalbermattenm** [comment]
I do not get the last point to do ("Location of translation links")

**Comment by rbovard** [comment]
I think you "solved" it with a new line

![image](https://user-images.githubusercontent.com/4549666/27790411-9a47152a-5ff0-11e7-992e-f36a734046e9.png)
