### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kalbermattenm** [geomapfish/geomapfish_website#16]
Each time I build the website, I get the following error:
```
C:\travail\gmf_website>Scripts\pelican.exe content
ERROR: Cannot find translations for language 'fr' in 'C:\travail\gmf_website\the
mes\translations' with domain 'messages'. Installing NullTranslations.
ERROR: Cannot find translations for language 'fr' in 'C:\travail\gmf_website\the
mes\translations' with domain 'messages'. Installing NullTranslations.
ERROR: Cannot find translations for language 'fr' in 'C:\travail\gmf_website\the
mes\translations' with domain 'messages'. Installing NullTranslations.
Done: Processed 0 articles, 0 drafts, 4 pages and 4 hidden pages in 0.58 seconds
.
Done: Processed 0 articles, 0 drafts, 4 pages and 4 hidden pages in 1.12 seconds
.
Done: Processed 0 articles, 0 drafts, 4 pages and 4 hidden pages in 2.20 seconds
.
```

This one is quite obvious because we currently only have German language support here:

https://github.com/geomapfish/geomapfish_website/tree/master/themes/translations/

@rbovard, what have you done to add German support ? (we should do the same for French...)

**Comment by rbovard** [comment]
I've done nothing, it's what I said in my PR #6. There is currently only german in this theme (see https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3/translations)

It's more a warning for me, it build but the theme is not translated...

**Comment by kalbermattenm** [comment]
OK, got it... sorry...

It is not so crucial in French... (because "Lang" not translated from English into French is not so important...)

Closing
