### ISSUE TITLE
Create community pages

### ISSUE THREAD

**Issue by kalbermattenm** [geomapfish/geomapfish_website#28]
Currently we do not have a proper "community" description...

**Comment by rbovard** [comment]
Also add some info about the PSC (at least a list)

**Comment by kalbermattenm** [comment]
Yes, this should be part of it, as well as the "charta" stuff from Luis... If you have any inspiration about writing a community description, feel free... 😉

**Comment by rbovard** [comment]
Yep but it was more to not forget it...

BTW @mriedo was not intending to write some content?

**Comment by kalbermattenm** [comment]
Fixed with #47
