### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by kalbermattenm** [geomapfish/geomapfish_website#36]
Get https://github.com/camptocamp/ngeo/blob/master/docs/features.md

(but I do not know how...)

**Comment by rbovard** [comment]
Some ideas:
* Via GitHub [API](https://developer.github.com/v3/repos/contents/)?
* `wget` equivalent of the RAW version?

With a batch...

**Comment by kalbermattenm** [comment]
Fixed with #47
