### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by rbovard** [geomapfish/geomapfish_website#46]
See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by rbovard** [comment]
@kalbermattenm I think C2C is managing the domain, am I right?

In the geomapfish.github.io settings, I see:
> Enforce HTTPS — Unavailable for your site because your domain is not properly configured to support HTTPS (geomapfish.org)

**Comment by kalbermattenm** [comment]
> @kalbermattenm I think C2C is managing the domain, am I right?

Yes, you are right. I remember @ebelo adding the CNAME.

**Comment by rbovard** [comment]
@ebelo Do you know if we can easily serve gmf.org via HTTPS?

**Comment by kalbermattenm** [comment]
You should send him a private email and CC @sbrunner...

**Comment by sbrunner** [comment]
It should be possible to enable it in 24 hours :-)

**Comment by rbovard** [comment]
It's working, thanks a lot!

For my information, what did you changed @sbrunner?

**Comment by sbrunner** [comment]
The configuration of the domain registration on Gandi...

**Comment by rbovard** [comment]
Okay, thanks :)

**Comment by kalbermattenm** [comment]
Thanks to both of you !
