### ISSUE TITLE
Add documentation link

### ISSUE THREAD

**Issue by ponceta** [geomapfish/geomapfish_website#66]
It would be great to have a direct access to the documentation

**from** https://geomapfish.org 

**to** https://camptocamp.github.io/c2cgeoportal/master/ 

![image](https://user-images.githubusercontent.com/8614223/74335593-d3b03980-4d9c-11ea-8771-b3af01e23771.png)

I did not find where to propose this.

**Comment by rbovard** [comment]
Good idea, thanks.

But I don't know if we can add an external link to the menu, I'll check.
