### ISSUE TITLE
Suggestion: Add link to https://github.com/camptocamp/geomapfish 

### ISSUE THREAD

**Issue by svavoi** [geomapfish/geomapfish_website#80]
Adding a new link to the Github Geomapfish-Account for creating and discussing new enhancements (https://github.com/camptocamp/geomapfish).

Add the moment the link goes to the c2cgeoportal repository. What do you think, is it better to replace it or to add a second link?

![image](https://user-images.githubusercontent.com/5998978/102349447-a37c8d00-3fa3-11eb-8041-4e6922a8a736.png)

**Comment by rbovard** [comment]
I think it's better to replace it (it's more "social" than the source code repo)
